### ISSUE TITLE
Categorical Variables with long tail

### ISSUE THREAD

**Issue by Nithanaroy** [entron/entity-embedding-rossmann#18]
Thanks for sharing your code serving it as a reference to learn from and understand the use case of embedding better. 

Our dataset is also tabular and have high cardinality columns (~6 million) like IP Address. Besides that 85% of IP Addresses appear only once in the dataset. What are your thoughts on using this technique to convert such a categorical column into euclidean space?

**Comment by entron** [comment]
If it only appears once you can not do anything about it I guess.

**Comment by Nithanaroy** [comment]
Yeah. What are some ways to handle such  high cardinality long tail categorical distributions?

**Comment by entron** [comment]
Never met such a problem myself. It would be great if you could share your learning here when you solve it.

**Comment by Nithanaroy** [comment]
I think it should be solved on case by case basis. For IP Address like column where each character (set) has a meaning and is of fixed length I came up with character one-hot encoding technique. Explained the idea and inspiration behind it at https://medium.com/@Nithanaroy/encoding-fixed-length-high-cardinality-non-numeric-columns-for-a-ml-algorithm-b1c910cb4e6d. However this may not make intuitive sense for other high cardinality categorical columns like user id.

**Comment by prekratko** [comment]
Did you think about using whois service (or reverse dns) to identify service provider from IP address? This way you can make more sense of addresses and categorize per service provider and country.

**Comment by Nithanaroy** [comment]
Yes, good point. I derive other features from it like geo and asn. This is a nice way to solve this long tail high cardinality problem.

Any ideas for user id column where there is no instrinsic meaning but only a unique representation of a member?

**Comment by prekratko** [comment]
In this context, there is much more correlation for a user to "belong" to specific service provider than to do anything with IP address itself. Cases of same username to span multiple providers is reality but I don't think there are too many cases like this.
Since IP address "travels" between users, it is not that much useful. Only when used to link some other data, it becomes useful.
So, based on this discussion, correlate address and username with service provider. This derived information seems pretty useful.

**Comment by entron** [comment]
As there is not more discusions I will close it.
